FROM multiarch/debian-debootstrap:arm64-stretch-slim
ARG GO_VERSION
ARG GOLINT_COMMITREF=
ARG GLIDE_COMMITREF=

# gcc for cgo
RUN apt-get update && apt-get install -y --no-install-recommends \
        g++ \
        gcc \
        libc6-dev \
        make \
        pkg-config \
        ca-certificates \
        git \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/local/go \
    && wget -O go.tgz "https://golang.org/dl/go${GO_VERSION}.linux-arm64.tar.gz" \
    && tar -C /usr/local -xzf go.tgz \
    && rm go.tgz; 

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
WORKDIR $GOPATH

COPY setup_tools.sh ./setup_tools.sh
RUN chmod +x setup_tools.sh && ./setup_tools.sh && rm ./setup_tools.sh